server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于与binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: root
                password: 123456
      bindings: # 服务的整合处理
        output: # 通道名称
          destination: studyExchange # 表示要使用的exchange名称定义
          context-type: application/json # 设置消息类型 json格式  文本则设置为“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔
    lease-expiration-duration-in-seconds: 5 # 超时时间
    instance-id: send-8801.com #在消息列表显示主机名称
    prefer-ip-address: true #访问的路径变为IP地址
