server:
  port: 8001

spring:
  application:
    name: cloud-patment-service
  # 全链路采集监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于0-1之间，1表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xin.cloud.entities

eureka:
  client:
    # 表示是否注册进Eureka server
    register-with-eureka: true
    # 表示是否从EurekaServer抓取已有的信息，集群必须为true
    fetch-registry: true
    service-url:
      # 注册入eureka集群
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 修改eureka中显示名称
    instance-id: payment8001
    # 访问路径显示IP地址
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间间隔，单位为妙（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒）超时将剔除服务
    lease-expiration-duration-in-seconds: 20