server:
  port: 9526

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PATMENT-SERVICE #匹配后使用服务名进行路由
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2020-06-22T11:18:09.926+08:00[Asia/Shanghai] #在此时间之后执行
#            - Before=2020-06-22T11:18:09.926+08:00[Asia/Shanghai] # 在此时间之前执行
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver] # 介于俩个时间之间
#            - Cookie=username, xin # 添加cookie信息: cookie name和regexp(正则表达式)
#            - Header=X-Request-Id, \d+ #如果请求具有名为X-Request-Id其值与\d+正则表达式匹配的header（即，其值为一个或多个数字），则此路由匹配。
#            - Host=**.somehost.org,**.anotherhost.org #通过参数中的主机地址作为匹配规则
#            - Method=GET,POST # 匹配请求方式
#            - Query=green # 查询参数匹配，必须包含本参数

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PATMENT-SERVICE #匹配后使用服务名进行路由
          predicates:
            Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-fateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
